server:
  port: 8082
spring:
  application:
    name: userService
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ
#        namespace: bbae9dc0-2502-4813-a380-6dfb929b58ae
#feign:
#  httpclient:
#    enabled: true # 支持HttpClient的开关
#    max-connections: 200 # 最大连接数
#    max-connections-per-route: 50 # 单个路径的最大连接数